<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SoundCore.EstructurasPropias</RootNamespace>
    <AssemblyName>SoundCore.EstructurasPropias</AssemblyName>
  </PropertyGroup>

</Project>
